# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: Geneva Trace Nuget Generation

on:
  push:
    branches: "*"
    paths:
      - "exporters/geneva-trace/**"
      - ".github/workflows/geneva_trace.yml"
  pull_request:
    branches: [main]
    paths:
      - "exporters/geneva-trace/**"
      - ".github/workflows/geneva_trace.yml"

permissions:
  contents: read
  
jobs:
  geneva-trace-nuget-generation:
    name: Geneva Trace
    runs-on: windows-latest
    steps:
    - name: github config
      run: git config --system core.longpaths true
    - uses: actions/checkout@v6.0.1
      with:
        submodules: 'recursive'
    - name: NuGet package generation
      env: 
        PackageVersion: 0.0.1
      run: |
        cd exporters\geneva-trace\tools && .\build-nuget.cmd
